### ISSUE TITLE
The problem is that when SAFARI is working - and I close it - Adguard still working - and gives a big PING in games - and I can not watch any movie online - I must wait downloading to long time ((( - why is it so?

### ISSUE THREAD

**Issue by Mityajko** [AdguardTeam/AdGuardMiniForMac#709] opened 2022-04-28 20:15 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8))
* Operating System: (e.g macOS High Sierra 10.13.6)
* Filters you use in AdGuard:
* Any other browser extensions you have installed:

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment] 2022-05-04 12:21
@Mityajko Hi! Looks like you might have chosen 'Remember my choice' once allowing the application to work in the background: https://uploads.adguard.com/adguard_dialog_window.png.
Try clicking 'Quit' in the [menu bar](https://uploads.adguard.com/menu_bar.png).

**Comment by Mityajko** [comment] 2022-05-04 12:34
I press quit every time when I close safari, I even deleted and installed
it again - the same situation

ср, 4 мая 2022 г., 15:21 Anna ***@***.***>:

**Comment by Birbber** [comment] 2022-05-04 12:49
@Mityajko That's weird. Have you tried quitting the process in Activity monitor?
What os do you have? And what version of AdGuard for Safari do you use?
I couldn't reproduce it on Monterey.

**Comment by Mityajko** [comment] 2022-05-04 13:04
I will answer when will be at home, thank you for responding

ср, 4 мая 2022 г., 15:49 Anna ***@***.***>:

**Comment by Mityajko** [comment] 2022-05-05 15:27
Hello again - here is all software info - i tried to do how you
recommended (push NO running in background - and "remember my choice") but
how you can see on screenshots - it doesn't work - it is still running when
safari is off

ср, 4 мая 2022 г. в 15:21, Anna ***@***.***>:

**Comment by Birbber** [comment] 2022-05-11 10:07
@Mityajko You haven't attached the screenshots. Please try again or describe your system and settings in a text form.
Also share the app logs. Here's what we need you to do:
* Make sure all Safari content blockers are enabled;
* Reproduce the issue and remember the exact time when it happened;
* Open the extension settings --> `Export logs and system info`;
* Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Birbber** [comment] 2022-05-16 08:48
@Mityajko Have you already sent it?

**Comment by Birbber** [comment] 2022-05-27 08:18
I'm closing this issue due to no reply. Please re-open if needed.

**Closed** 2022-05-27 08:18 UTC
Labels: Question, Resolution: Cannot Reproduce, Priority: P4, Status: Done
