### ISSUE TITLE
Youtube won't load a video without refreshing.

### ISSUE THREAD

**Issue by JohnnyMonz93** [AdguardTeam/AdGuardMiniForMac#1016] opened 2024-09-15 15:54 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 1.11.17 (build 329, CT 2.0.44)

### Environment

```markdown
- OS: 14.6.1 (23G93)
- Safari version: 17.6

AdGuard seems to have an issue with YouTube. It seems that every video I load won't skip ads until I refresh the page. The page will hang until the first refresh for every video I try to watch.
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Load a YouTube video
2. Watch the page hang and not load the video
3. Refresh to watch the video

### Expected Behavior

Every YouTube video should load without having to refresh the page

### Actual Behavior

Videos should play without having to refresh the page.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment] 2024-09-18 14:06
@JohnnyMonz93, hello! Please update AdGuard for Safari to latest 1.11.19 version and check for filter updates.

**Comment by alexx7311** [comment] 2024-09-23 10:51
@JohnnyMonz93 We'll close the issue for now. Please leave a comment if the problem is still relevant.

**Closed** 2024-10-08 13:46 UTC
Labels: Resolution: Cannot Reproduce, Priority: P4, Status: Done
