### ISSUE TITLE
Bugs when starting the app

### ISSUE THREAD

**Issue by Kl4us83** [AdguardTeam/AdGuardMiniForMac#812] opened 2023-02-25 16:43 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.11

### Environment

```markdown
- OS:Ventura 13.2.1
- Safari version: 16.3
```

### What filters do you have enabled?

No filters

### Issue Details

Steps to reproduce:
1. Start Mac OS
2. Home page of the app that appears when the operating system starts up
3. Home page that doesn't disappear but you have to do it manually
4.

### Actual Behavior

As soon as you start the OS, the AdGuard extension for Safari starts regularly but the start page appears fixed on the display and you have to remove it with a click

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment] 2023-02-27 08:14
@Kl4us83 
We are aware of the issue and are currently working on a fix.
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release).

Closed as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Closed** 2023-02-27 08:15 UTC
Labels: Duplicate, Resolution: Duplicate, Priority: P4, Status: Done
