### ISSUE TITLE
Stop prompting to update all the time

### ISSUE THREAD

**Issue by cgarrovillo** [AdguardTeam/AdGuardMiniForMac#813] opened 2023-02-25 20:17 UTC
### Issue Details

Just update it in the background. User intervention for this makes it such a hassle and devalues the product. 

### Proposed solution

Update in the background

**Comment by jslawler** [comment] 2023-02-26 06:55
Possible solution, which AdGuard already uses in AdGuard for macOS from memory.

[Sparkle Project](https://sparkle-project.org) allows for automatic upgrades. Refer to [here](https://sparkle-project.org/documentation/customization/). Setting the info.plist `SUAllowsAutomaticUpdates` boolean type to `True` will always allow automatic updates even if automatic checking of updates is disabled.

**Comment by Plastonick** [comment] 2023-02-28 15:13
I'm at the point where the only thing left to block is the AdGuard window constantly popping up.

**Comment by Versty** [comment] 2023-03-01 10:06
@cgarrovillo Hi! Closing your feature request as a duplicate of #789.

**Comment by Versty** [comment] 2023-03-01 10:15
@Plastonick We are working on a fix for the unintended appearance of the settings window. 
You can track the progress or discuss in #805.

**Closed** 2023-03-01 10:16 UTC
Labels: Duplicate, Feature request, Resolution: Duplicate, Priority: P4, Status: Done
