### ISSUE TITLE
AdGuard for Safari prevents iCloud Private Relay from being enabled in MacOS 14 (#816396)

### ISSUE THREAD

**Issue by Ghibelline** [AdguardTeam/AdGuardMiniForMac#898] opened 2023-09-28 08:27 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: 14.0
- Safari version: 17.0 (19616.1.27.211.1)
```

### Issue Details

Steps to reproduce:
1. Install AdGuard for Safari
2. enable iCloud Private Relay
3. iCloud Private Relay is 'unavailable'

### Expected Behavior

I expected Private Relay to work fine with AdGuard enabled, as it did in the version of Safari in MacOS 13.

### Actual Behavior

System Settings tells me that Private Relay is unavailable due to extension settings. AdGuard for Safari is the only extension I have installed. I uninstalled it and rebooted my computer and Private Relay worked fine, only to become unavailable again when I reinstalled AdGuard.

### Screenshots

![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/21246366/d0a55ab7-969a-4b86-a7b6-958e24621719)
![image](https://github.com/AdguardTeam/AdGuardForSafari/assets/21246366/3a03c096-56e7-407d-b552-9a7be4bfc49f)

**Comment by alexx7311** [comment] 2023-10-05 10:16
@Ghibelline We couldn't reproduce the problem. Do you have AdGuard for Mac installed, or do you only have AdGuard for Safari? Do you use AdGuard DNS?

**Comment by alexx7311** [comment] 2023-10-10 16:31
@Ghibelline If we don't get a response, the issue will be closed in a few days.

**Closed** 2023-10-16 12:55 UTC
Labels: Resolution: Cannot Reproduce, Priority: P4, Status: Done
