### ISSUE TITLE
AdGuard for Safari won't start by icon double-click

### ISSUE THREAD

**Issue by avincent98144** [AdguardTeam/AdGuardMiniForMac#675] opened 2021-12-26 15:22 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [] I am running the latest version
- [] I checked the documentation and found no answer
- [] I checked to make sure that this issue has not already been filed

### Issue Details

* AdGuard for Safari version: 1.10.4
* Environment name and version: (e.g. Safari 11.1.2 (13605.3.8)) STP 137
* Operating System: (e.g macOS High Sierra 10.13.6) 12.1
* Filters you use in AdGuard: see log
* Any other browser extensions you have installed: see log

* **Version of AdGuard for Safari:**
  * 
* **Environment name and version:**
  * 
* **Operating system and version:**
  * 
* **Filters you use in AdGuard:**
  * 
* **Any other browser extensions you have installed:**
  * 

### Expected Behavior

app to run as usual

### Actual Behavior

upon reboot the app will not start by the usual double-click on the icon. however, the workaround is to run the executable and hide TERMINAL

### Screenshots

attached

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment] 2021-12-27 16:47
@avincent98144 Could not reproduce on our test device. Maybe you could show us a screen recording?

**Comment by avincent98144** [comment] 2021-12-27 16:55
Since it has always been intermittent, I will record it when it happens next time. 

Note: All that happens is that is 100% stops any site customized settings ignore any custom rules already set.

Not sure what a screen recording is going to do other than prove my point visually.

**Comment by Birbber** [comment] 2021-12-28 08:16
So the issue is connected to [#672](https://github.com/AdguardTeam/AdGuardForSafari/issues/672). I will close this one then. 
Please don't create a new one if it's connected to the mentioned issue. You can always add comments to the existing one.

**Closed** 2021-12-28 08:17 UTC
Labels: Resolution: Duplicate, Priority: P4, Status: Done

**Comment by avincent98144** [comment] 2021-12-28 15:03
This error behaviour has begun again. The app can only be opened by running the executable. If I quit TERMINAL, the app quits.  

1 in 5 reboots the app will start as expected. The other times I have to do this TERMINAL work around.

Please advise

**Comment by avincent98144** [comment] 2022-01-01 16:22
Broken again as already described. Reboots no longer resolve this intermittent ‘quitting’ of custom element removal on all pages.

Same in Safari as well.

**Comment by avincent98144** [comment] 2022-01-13 19:50
Following up!

**Comment by avincent98144** [comment] 2022-01-13 19:50
following up!

**Comment by avincent98144** [comment] 2022-01-13 19:51
following up!
