### ISSUE TITLE
YouTube video playback does not work with AdGuard for Safari enabled

### ISSUE THREAD

**Issue by Ciccio-lo** [AdguardTeam/AdGuardMiniForMac#935] opened 2023-11-19 10:04 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.15 (build 309, CT 2.0.44)

### Environment

```markdown
- OS: Big Sur 11.4 (20F71)
- Safari version: 14.1.1 (16611.2.7.1.4)
```

### What filters do you have enabled?

EasyList Italy

### Issue Details

Steps to reproduce:
1. visit "youtube.com" in Safari; 
2. click to reproduce any video; 
3. sometimes the site show a page that says something like "You are offline, connect to internet", or the video won't play. In both case you have to pause ADGUARD and refresh the page. 
<img width="801" alt="Schermata 2023-11-19 alle 11 01 30" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/151434447/0e6824cb-d074-4c11-96c6-1d8a19fa8865">
<img width="1065" alt="Schermata 2023-11-19 alle 11 02 14" src="https://github.com/AdguardTeam/AdGuardForSafari/assets/151434447/10c602d2-dddb-4cf1-9ee7-942c6963a900">

### Expected Behavior

The video should be played. 

### Actual Behavior

The video won't play or the page doesn't load properly.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by crgmrgn** [comment] 2023-11-19 14:36
See #884, try the v1.11.16 beta, it seems to address this ...

**Comment by Ciccio-lo** [comment] 2023-11-19 17:49
> See #884, try the v1.11.16 beta, it seems to address this ...

Thank you! how can I update it to the beta version?

**Comment by crgmrgn** [comment] 2023-11-21 18:18
v.1.11.16 has now been formally released, so you can update to it from the App Store or via direct download.

**Comment by alexx7311** [comment] 2023-11-22 14:08
> > See #884, try the v1.11.16 beta, it seems to address this ...
> 
> Thank you! how can I update it to the beta version?

@Ciccio-lo You can find all the links at https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.11.16.324-release
We will close this issue as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/884

**Closed** 2023-11-22 14:08 UTC
Labels: Resolution: Duplicate, Priority: P4, Status: Done
