### ISSUE TITLE
Adguard settings annoyingly pops up on every reboot

### ISSUE THREAD

**Issue by RyanRhea** [AdguardTeam/AdGuardMiniForMac#814] opened 2023-02-26 17:19 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

latest

### Environment

```markdown
- OS: venture (latest)
- Safari version: (latest)
```

### Issue Details

Steps to reproduce:
1. install the software
2. reboot the machine
3. prepare to be annoyed

### Expected Behavior

Adguard gets installed, configured and then fucks right the fuck off like any other set it and forget it software.  I DO NOT expect to be reminded that this piece of shit even still exists. It's a tool, not a cool piece of software I want to be reminded of and interact with every fucking day. 

### Actual Behavior

You devs can't figure out how to keep the client from auto launching on reboot, even though every step has been taken to prevent it on my end.  There must be some nefarious monetization of this, but I just can't figure how how or why.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Stop being douchey and fix yer shit.

**Comment by Versty** [comment] 2023-02-27 08:20
@RyanRhea 
We are aware of the issue and are currently working on a fix.
As a temporary solution you can uninstall, then download and install the version from [this link](https://agrd.io/safari_release).

Closed as a duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/805

**Closed** 2023-02-27 08:21 UTC
Labels: Duplicate, Resolution: Duplicate, Priority: P4, Status: Done
