### ISSUE TITLE
AdGuard 1.8.8 for BigSur on Safari 14.0.1 doesn't block ads

### ISSUE THREAD

**Issue by GianGus** [AdguardTeam/AdGuardMiniForMac#461] opened 2020-11-30 01:45 UTC
Hi, I have an iMac 21' 4K 2017 with the latest MacOS BigSur 11.0.1 and AdGuard 1.8.8 correctly set-up and installed (with all extensions activated in Safari) and I see that ads are everywhere, it stopped working correctly and it doesn't block Ads (maybe only few of those are blocked). Are there any errors with the latest AdGuard version? Is there a thing to solve the problem? I see that in Chrome AdBlock runs correctly.

Thank you

**Comment by einsteinbqat** [comment] 2020-11-30 03:48
@GianGus 
> Hi, I have an iMac 21' 4K 2017 with the latest MacOS BigSur 11.0.1 and AdGuard 1.8.8 correctly set-up and installed (with all extensions activated in Safari) and I see that ads are everywhere, it stopped working correctly and it doesn't block Ads (maybe only few of those are blocked). Are there any errors with the latest AdGuard version? Is there a thing to solve the problem? I see that in Chrome AdBlock runs correctly.
> 
> Thank you

For now, what I did on my MBA that works it to completely remove the downloaded 1.8.8 version from GitHub/AdGuard.com, and install the 1.8.8 version from the App Store. Then it should work until they fix the issue.

**Comment by openfred65** [comment] 2020-11-30 08:39
I am using a MacBook Air M1 with Safari Version 14.0.1 (16610.2.11.51.8) and Adguard from App Store.
Experiencing the same issue : many Ads. With version 1.8.6 and from now 1.8.8.
Tried Adguard on iPad, no issue all add blocked. 
Tried Adguard on Firefox 84beta5 on the same MBA M1, and all ads are blocked.

Tests done on speedtest.net
I activated all Adguard filters (Advanced, Others, Privacy, Security, Social) in Safari / Preferences / Extensions tabs, and within Adguard app itself. I even exported parameters from Firefox to import them in Safari and there are still all ads.

Adguard is not working on Safari 14.0.1 Big Sur 11.0.1

<img width="1380" alt="Capture d’écran 2020-11-30 à 09 36 06" src="https://user-images.githubusercontent.com/75244266/100586486-88492680-32ef-11eb-8082-1ae32ddbce4d.png">

**Comment by GianGus** [comment] 2020-11-30 09:18
> @GianGus
> 
> > Hi, I have an iMac 21' 4K 2017 with the latest MacOS BigSur 11.0.1 and AdGuard 1.8.8 correctly set-up and installed (with all extensions activated in Safari) and I see that ads are everywhere, it stopped working correctly and it doesn't block Ads (maybe only few of those are blocked). Are there any errors with the latest AdGuard version? Is there a thing to solve the problem? I see that in Chrome AdBlock runs correctly.
> > Thank you
> 
> For now, what I did on my MBA that works it to completely remove the downloaded 1.8.8 version from GitHub/AdGuard.com, and install the 1.8.8 version from the App Store. Then it should work until they fix the issue.

Hi, thanks for the tip but unfortunately the version i have installed comes from the mac app store and not from github or adguard.com

**Comment by ameshkov** [comment] 2020-11-30 10:27
We need to know what exact filter lists you're all using.

The simple way to share this is to export settings from AdGuard for Safari.

**Comment by GianGus** [comment] 2020-11-30 10:31
> We need to know what exact filter lists you're all using.
> 
> The simple way to share this is to export settings from AdGuard for Safari.

Here it is mine! Thank you
[adguard-settings-20201030_113025.json.zip](https://github.com/AdguardTeam/AdGuardForSafari/files/5615374/adguard-settings-20201030_113025.json.zip)

**Comment by openfred65** [comment] 2020-11-30 10:32
Here is the export file. I just renamed .json file extension to .json.txt so that Github interface accept the file.
By the way, please not that having to activate all filters in "Adguard Preferences / Filters" and also in "Safari / Preferences /  Extensions tab" is a bit weird.

[adguard-settings-20201030_112833.json.txt](https://github.com/AdguardTeam/AdGuardForSafari/files/5615362/adguard-settings-20201030_112833.json.txt)

**Comment by rccrdtcchn** [comment] 2020-11-30 11:28
Had the same problem and I resolved by resetting language specific filter as suggested [https://www.reddit.com/r/Adguard/comments/jukn4b/compilation_error_with_adblock_general/](here)
Apparently something was causing a compilation error in the General filter, hope this can help sorting out the cause.

**Comment by openfred65** [comment] 2020-11-30 11:38
True, and even more :

For me just deselecting and selecting back the language filter sorted out the issue !

**Comment by rccrdtcchn** [comment] 2020-11-30 11:47
> True, and even more :
> 
> For me just deselecting and selecting back the language filter sorted out the issue !

Thats what I did too, maybe "resetting" was not the right term to use.
Also before doing that I tried reinstalling both from the App Store and GitHub but it did not resolve the issue

**Comment by GianGus** [comment] 2020-11-30 11:53
> True, and even more :
> 
> For me just deselecting and selecting back the language filter sorted out the issue !

I try to deselect and reselect the language filter and that's it, all seem to work right now! That's kind of weird!

**Closed** 2020-12-04 16:29 UTC
Labels: Bug, Resolution: Done, High, Priority: P4, Version: Safari v1.8.9, Status: Done
