### ISSUE TITLE
`Compilation failed` for Adguard Base Filter on macOS 11.6.5 + Safari 15.4

### ISSUE THREAD

**Issue by sangyounkim** [AdguardTeam/AdGuardMiniForMac#699] opened 2022-04-04 08:48 UTC
### Issue Details

* AdGuard for Safari version: v1.11.3
* Environment name and version: Safari 15.4 (16613.1.17.1.13, 16613)
* Operating System: MacOS 11.6.5 (20G527)
* Filters you use in AdGuard: Base, Tracking Protection, List-KR, User Filters
* Any other browser extensions you have installed: None

### Expected Behavior
Filters should be compiled without errors.

### Actual Behavior
Accessing **General** > **Content Blockers** shows Adguard General, Privacy as `Compilation failed`.
Ads are not being blocked.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="959" alt="image" src="https://user-images.githubusercontent.com/1451821/161506977-caf290f2-66c0-4538-b20b-859e0646066c.png">

</details>

### Additional Information
I've attempted the suggested fix in https://github.com/AdguardTeam/AdGuardForSafari/issues/418#issuecomment-729262654 to turn off language-specific filters, but left with the same issue. Tried to turn off all filters, then turn on Adguard Base Filter only but the compilation error does not seem to go away.

**Comment by ameshkov** [comment] 2022-04-04 08:49
Hi, what rules do you have in the User Rules? If there's nothing private, could you please share them with us?

Also, please try removing all rules there.

**Comment by tvinzz** [comment] 2022-04-04 08:54
@sangyounkim, please check all content-blockers are enabled in Safari preferences

**Comment by sangyounkim** [comment] 2022-04-04 09:05
@ameshkov 
<details>
<summary>My user rules:</summary>

```
@@||googlesyndication.com$domain=spotvnow.co.kr

! 2021-08-28 https://www.spotvnow.co.kr
@@||imasdk.googleapis.com/js/sdkloader/ima3.js$xhr,domain=spotvnow.co.kr
```

</details>

@tvinzz I've used Adguard in the past without compilation issues (only enabling what I need, which are Adguard General and Privacy). I've tried turning them all on, but compilation error still exists.

In addition, I've attempted a clean install of the extension by removing Adguard related contents under `~/Library/Group\ Containers/` and `~/Library/Containers` but the compilation error still exists.

**Comment by Birbber** [comment] 2022-04-04 09:21
@sangyounkim Hi, could you share the app logs?
Here's what we need you to do:

- Make sure all Safari content blockers are enabled;
- Reproduce the issue and remember the exact time when it happened;
- Open the extension settings --> Export logs and system info;
- Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by sangyounkim** [comment] 2022-04-04 09:37
@Birbber Sent the archive to the email above.

**Comment by sangyounkim** [comment] 2022-04-04 12:12
I happened to upgrade from Big Sur to Monterey and for some reason the problem seems to have gone away. I am suspecting Safari build version has changed since upgrading (BigSur:  15.4 (16613.1.17.1.13, 16613), Monterey: 15.3 (17612.4.9.1.8))

Closing this issue, since I no longer have the issue. I appreciate all your timely responses to my issue, thanks 🙏🏼

**Comment by ameshkov** [comment] 2022-04-07 11:19
Got another report with the very same versions of macOS and Safari:

> Environment name and version: Safari 15.4 (16613.1.17.1.13, 16613)
> Operating System: MacOS 11.6.5 (20G527)

**Comment by adunning** [comment] 2022-04-07 14:24
It must have been the upgrade from Big Sur to Monterey that fixed it for @sangyounkim; unfortunately my computer is too old.

**Comment by dmart77** [comment] 2022-04-09 15:36
[2022-04-09 18:18:32.659] [info] Setting content blocker json for com.adguard.safari.AdGuard.BlockerCustom.Rules count: 1. Json length=109;
[2022-04-09 18:18:32.659] [info] Content-blocker updating com.adguard.safari.AdGuard.BlockerCustom
[2022-04-09 18:18:32.662] [info] Safari browser version: 15.4
[2022-04-09 18:18:32.662] [info] ConverterTool version: 2.0.25
[2022-04-09 18:18:32.662] [info] Conversion of 37149 rules started..
[2022-04-09 18:18:32.663] [info] CONVERTER PATH: /Applications/AdGuard for Safari.app/Contents/Resources/libs/ConverterTool
[2022-04-09 18:18:32.803] [info] Content-blocker com.adguard.safari.AdGuard.BlockerExtension set result : {"result":"error", "error":{"domain":"WKErrorDomain", "code":2, "descr":"The operation couldn’t be completed. (WKErrorDomain error 2.)", "userInfo":"{
    NSHelpAnchor = "Rule list compilation failed: Invalid string in the trigger flags array.";
}"}

**Comment by dmart77** [comment] 2022-04-16 12:33
Re-installing extension did not help.
`Content blockers
AdGuard General
Compilation failed
Enabled: AdGuard Base filter
AdGuard Privacy
Compilation failed
Enabled: AdGuard Tracking Protection filter
AdGuard Social
Compilation failed
Enabled: AdGuard Social Media filter and AdGuard Annoyances filter`

**Comment by tvinzz** [comment] 2022-04-29 11:51
The new resource types `websocket`, `fetch` and `other` were announced for Safari 15.
But actually they don't supported in macOS Big Sur + Safari 15.

Examples of problematic rules:
* rule: `||example.org$other`
converted to json: `[{\"trigger\":{\"url-filter\":\"^[htpsw]+:\\\\/\\\\/([a-z0-9-]+\\\\.)?example\\\\.org\",\"resource-type\":[\"other\"]},\"action\":{\"type\":\"block\"}}]`
so `"resource-type":["other"]` - fails the content-blocker compilation.
* rule: `||example.org$~image`
converted to json: `[{\"trigger\":{\"url-filter\":\"^[htpsw]+:\\\\/\\\\/([a-z0-9-]+\\\\.)?example\\\\.org\",\"resource-type\":[\"style-sheet\",\"script\",\"media\",\"fetch\",\"other\",\"websocket\",\"font\",\"ping\",\"document\"]},\"action\":{\"type\":\"block\"}}]`
so `"resource-type":["fetch", "other", "websocket"]` - fails the content-blocker compilation.

This issue will be fixed in next AdGuard for Safari update coming soon.

**Comment by tvinzz** [comment] 2022-05-10 19:44
You're welcome to test the new version in Apple Testflight: https://testflight.apple.com/join/c31mEr6q
Looking forward for your feedback.

**Comment by hrvstr** [comment] 2022-05-11 06:17
Looks like TestFlight is not supported on 11.6.5 anymore and this bug only affects Big Sur.

![Bildschirmfoto 2022-05-11 um 08 13 15](https://user-images.githubusercontent.com/4610008/167781418-9b1f78f0-b896-4698-9f0a-30d2d0f1a5d5.png)

**Comment by hrvstr** [comment] 2022-05-12 09:45
I just found out that I don't need the TestFlight app to get the beta. I found a [link](https://agrd.io/safari_beta) in the README of this GitHub repo.

I now have version 1.11.4 installed and now even more content blockers are failing to compile. Before that I had the stable release 1.11.3 installed and only "AdGuard General" and "AdGuard Privacy" failed.

I tried to erase all settings by deleting the app including all associated PLIST files with [AppCleaner](https://freemacsoft.net/appcleaner/).

**Comment by tvinzz** [comment] 2022-05-12 10:17
@hrvstr, did you install v1.11.4 beta over v1.11.3 mas?
AppCleaner is not a proper way for pure install, please use the following instructions:
* Disable all of them and close Safari browser
* Close AdGuard for Safari
* Delete the following directories:
  * ~/Library/Application Support/AdGuardSafariApp
  * ~/Library/Containers/ - all directories started with com.adguard.safari.AdGuard (if there’s any)
  * ~/Library/GroupContainers/TC3Q7MAJXF.com.adguard.safari.AdGuard
  * ~/Library/Preferences/com.adguard.safari.AdGuard.plist
* Quit all “AdGuard” and “cfprefsd” processes in Activity monitor
* Reinstall AdGuard for Safari

**Comment by hrvstr** [comment] 2022-05-12 13:53
I followed the steps you described but the content blockers still fail to compile.

The only thing I did differently is that the folder `TC3Q7MAJXF.com.adguard.safari.AdGuard` is actually in `~/Library/Group Containers/` not `~/Library/GroupContainers/` but that was just a typo I guess.

Should I send the logs somewhere? Are they safe to post publicly?

**Comment by Birbber** [comment] 2022-05-13 08:02
@hrvstr Could you please share the app logs?
Here's what we need you to do:
* Make sure all Safari content blockers are enabled;
* Reproduce the issue and remember the exact time when it happened;
* Open the extension settings --> Export logs and system info;
* Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by Birbber** [comment] 2022-05-13 10:17
@hrvstr Thanks, received the logs.

**Comment by ameshkov** [comment] 2022-05-14 17:22
@tvinzz we received the logs. According to it, the content blocker was again compiled with Safari 15 features.

**Comment by ameshkov** [comment] 2022-05-14 17:31
Tbh, it looks like an old beta, not the new one.

@hrvstr the version 11.4 is already available on App Store, could you please try installing it.

In the meantime, we should check what version we have in the standalone beta channel.

**Comment by hrvstr** [comment] 2022-05-15 10:22
Doing a clean install (using your instructions) of version 1.11.4 stable from the App Store fixed the issue for me. Content blockers are compiling no matter how many filters I activate. Thanks for the help!

**Closed** 2022-08-10 12:04 UTC
Labels: Resolution: Fixed, Version: Safari v1.11.4, Priority: P4, Status: Done
