### ISSUE TITLE
YouTube is detecting AdGuard – again

### ISSUE THREAD

**Issue by vitamin-c-gmbh** [AdguardTeam/AdGuardMiniForMac#936] opened 2023-11-23 21:06 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I made sure all content blockers are enabled in Safari settings
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.14

### Environment

```markdown
- OS: Sonoma 14.1.1
- Safari version: 17.1
```

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Open YouTube
2. Klick play
3. AdBlocker-Warning flickers up real quick, then the YT-window turns black, YT logo appears in the center of the video area.

### Expected Behavior

Ads blocked, videos playing

### Actual Behavior

Ads blocked, videos too (by YT, though)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by crgmrgn** [comment] 2023-11-24 00:14
Latest version is v1.11.16 which resolves the YT playback issues on secondary clicks and their active adblocking (until YT take further steps?)

**Comment by alexx7311** [comment] 2023-11-24 12:29
Closed as duplicate of #913

**Closed by alexx7311** 2023-11-24 12:29 UTC
Labels: Resolution: Duplicate, Priority: P4, Status: Done
