### ISSUE TITLE
Preferences window now appears when waking from sleep

### ISSUE THREAD

**Issue by dtoub** [AdguardTeam/AdGuardMiniForMac#876] opened 2023-08-01 13:43 UTC
### AdGuard version

1.11.13

### Browser version

Safari 17.0

### OS version

Ventura 13.5

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1.Sleep your computer
2.Wake it up
3.The AdGuard preferences launch and appear on my screen
4. Never used to happen except every time I started up and that was finally (too long, but finally) resolved. Now, it appears every time I wake my MacBook Pro from sleep. 

### Expected Behavior

Preferences should not appear unless invoked by the user

### Actual Behavior

As above-it appears every time I wake the computer from sleep. So I've switched back to 1Blocker for now.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment] 2023-08-02 16:56
@dtoub I've moved your issue to the right repo.

**Comment by vozersky** [comment] 2023-08-29 15:52
duplicate of https://github.com/AdguardTeam/AdGuardForSafari/issues/875

**Closed by vozersky** 2023-08-29 15:52 UTC
Labels: Bug, Resolution: Duplicate, Priority: P4, Status: Done
